default: gen lint
# llvm_path  := "/usr/lib64/libclang.so"
#llvm_path  := /usr/lib64/clang"
# llvm_path  := "/usr/lib64/libclang.so.14"
#/home/logan/Android/Sdk/ndk/21.4.7075529/toolchains/renderscript/prebuilt/linux-x86_64/lib64/libclang.so
#export CPATH="$(clang -v 2>&1 | grep "Selected GCC installation" | rev | cut -d' ' -f1 | rev)/include"
#env "AR_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
#env "CC_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" \

llvm_path := ""
#export REPO_DIR="$PWD"; cd /; flutter_rust_bridge_codegen \

gen:
    export REPO_DIR="$PWD"; cd /; flutter_rust_bridge_codegen \
        --rust-input "$REPO_DIR/native/src/api.rs" \
        --dart-output "$REPO_DIR/lib/bridge_generated.dart" \
        --c-output "$REPO_DIR/ios/Runner/bridge_generated.h" \
        --c-output "$REPO_DIR/macos/Runner/bridge_generated.h"
    flutter pub run build_runner build
lint:
    cd native && cargo fmt
    dart format .

clean:
    flutter clean
    cd native && cargo clean

# vim:expandtab:sw=4:ts=4
